- name: "Build"
  run: "./gradlew classes"
- name: "Test"
  run: "./gradlew test"
- name: "Test coverage"
  run: "./gradlew jacocoRootReport jacocoCoverageVerification"
- name: Archive code coverage results
  uses: actions/upload-artifact@v2
  with:
    name: code-coverage-report
    path: build/reports/jacoco/html/
    retention-days: 2
- name: "Sonar Qube"
  if: always()
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  run: "./gradlew sonarqube --info"